apiVersion: v1
kind: Secret
metadata:
  name: aiverse-secrets
type: Opaque
data:
  # Values are:
  # database-url: postgresql+asyncpg://aiverse_user:aiverse_pass@postgres:5432/aiverse_db
  # secret-key: change-me-in-production
  database-url: cG9zdGdyZXNxbCthc3luY3BnOi8vYWl2ZXJzZV91c2VyOmFpdmVyc2VfcGFzc0Bwb3N0Z3Jlczo1NDMyL2FpdmVyc2VfZGI=
  secret-key: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
